apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - grafana.yaml

# Generate ConfigMap from our existing JSON dashboard schema dynamically
configMapGenerator:
  - name: grafana-dashboard-json
    files:
      - laptopzone-overview.json=laptopzone-overview.json

