apiVersion: v1
kind: Service
metadata:
  name: laptopzone-backend
  labels:
    app: laptopzone-backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: laptopzone-backend
